/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Main.java to edit this template
 */
package Mockup_Project;

import java.awt.CardLayout;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;

public class mockup2 extends javax.swing.JFrame {

    CardLayout cardMenu;

    public mockup2() {
        initComponents();
        cardMenu = (CardLayout) (jPanel2.getLayout());
        setImage();
    }

    //masih error 
    public void setImage() {
        ImageIcon icon = new ImageIcon("/Images/pakis.jpg");
        Image image = icon.getImage().getScaledInstance(750, 500, Image.SCALE_SMOOTH);
        jLabelItem1.setIcon(new ImageIcon(image));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelDashBoard1 = new javax.swing.JLabel();
        jLabelShop = new javax.swing.JLabel();
        jLabelCart = new javax.swing.JLabel();
        jLabelCart1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabelGreeting1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanelItem1 = new javax.swing.JPanel();
        jLabelItem1 = new javax.swing.JLabel();
        jSpinnerItem1 = new javax.swing.JSpinner();
        jButtonBuy1 = new javax.swing.JButton();
        jLabelItemName1 = new javax.swing.JLabel();
        jPanelItem2 = new javax.swing.JPanel();
        jLabelItem2 = new javax.swing.JLabel();
        jSpinnerItem2 = new javax.swing.JSpinner();
        jButtonBuy2 = new javax.swing.JButton();
        jLabelItemName2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(43, 235, 69));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabelDashBoard1.setBackground(new java.awt.Color(91, 243, 126));
        jLabelDashBoard1.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabelDashBoard1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDashBoard1.setText("DASHBOARD ");
        jLabelDashBoard1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelDashBoard1MouseClicked(evt);
            }
        });

        jLabelShop.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabelShop.setText("BELANJA");
        jLabelShop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelShopMouseClicked(evt);
            }
        });
        jLabelShop.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jLabelShopKeyPressed(evt);
            }
        });

        jLabelCart.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelCart.setText("KERANJANG");
        jLabelCart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCartMouseClicked(evt);
            }
        });

        jLabelCart1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelCart1.setText("DAFTAR TRANSAKSI");
        jLabelCart1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCart1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelDashBoard1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jLabelCart1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelCart)
                                    .addComponent(jLabelShop))))
                        .addGap(0, 15, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabelDashBoard1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(109, 109, 109)
                .addComponent(jLabelShop, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(174, 174, 174)
                .addComponent(jLabelCart)
                .addGap(147, 147, 147)
                .addComponent(jLabelCart1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabelShop.getAccessibleContext().setAccessibleName("jLabelShop\n");
        jLabelCart.getAccessibleContext().setAccessibleName("jLabelCart");

        jPanel2.setLayout(new java.awt.CardLayout());

        jLabelGreeting1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabelGreeting1.setText("Halo !! , Selamat datang di toko Heavy Rotation 17 \nSelamat berbelanjaaa!!!");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(jLabelGreeting1, javax.swing.GroupLayout.PREFERRED_SIZE, 674, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(400, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(202, 202, 202)
                .addComponent(jLabelGreeting1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(525, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel5, "card4");

        jLabel3.setText("ok ini label ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 642, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(500, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(867, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel3, "card3");

        jPanelItem1.setBackground(new java.awt.Color(255, 255, 255));

        jLabelItem1.setBackground(new java.awt.Color(148, 242, 120));
        jLabelItem1.setIcon(new javax.swing.ImageIcon("D:\\USD_JAVA_OOP\\PBOL\\Praktek\\src\\main\\java\\Images\\lodeh.jpg")); // NOI18N
        jLabelItem1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jSpinnerItem1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jSpinnerItem1KeyPressed(evt);
            }
        });

        jButtonBuy1.setText("Beli");
        jButtonBuy1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuy1ActionPerformed(evt);
            }
        });

        jLabelItemName1.setBackground(new java.awt.Color(0, 0, 0));
        jLabelItemName1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelItemName1.setForeground(new java.awt.Color(0, 0, 0));
        jLabelItemName1.setText("TANAMAN PAKIS");

        javax.swing.GroupLayout jPanelItem1Layout = new javax.swing.GroupLayout(jPanelItem1);
        jPanelItem1.setLayout(jPanelItem1Layout);
        jPanelItem1Layout.setHorizontalGroup(
            jPanelItem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelItem1Layout.createSequentialGroup()
                .addGroup(jPanelItem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelItem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanelItem1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabelItem1, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanelItem1Layout.createSequentialGroup()
                            .addGap(23, 23, 23)
                            .addComponent(jButtonBuy1)
                            .addGap(188, 188, 188)
                            .addComponent(jSpinnerItem1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelItem1Layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(jLabelItemName1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelItem1Layout.setVerticalGroup(
            jPanelItem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelItem1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelItem1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(jLabelItemName1)
                .addGap(18, 18, 18)
                .addGroup(jPanelItem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinnerItem1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBuy1)))
        );

        jPanelItem2.setBackground(new java.awt.Color(255, 255, 255));

        jLabelItem2.setBackground(new java.awt.Color(148, 242, 120));
        jLabelItem2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jSpinnerItem2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jSpinnerItem2KeyPressed(evt);
            }
        });

        jButtonBuy2.setText("Beli");
        jButtonBuy2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuy2ActionPerformed(evt);
            }
        });

        jLabelItemName2.setBackground(new java.awt.Color(0, 0, 0));
        jLabelItemName2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelItemName2.setForeground(new java.awt.Color(0, 0, 0));
        jLabelItemName2.setText("TANAMAN BONSAI\n");

        javax.swing.GroupLayout jPanelItem2Layout = new javax.swing.GroupLayout(jPanelItem2);
        jPanelItem2.setLayout(jPanelItem2Layout);
        jPanelItem2Layout.setHorizontalGroup(
            jPanelItem2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelItem2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelItem2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelItem2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jButtonBuy2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSpinnerItem2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
            .addGroup(jPanelItem2Layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addComponent(jLabelItemName2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(122, Short.MAX_VALUE))
        );
        jPanelItem2Layout.setVerticalGroup(
            jPanelItem2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelItem2Layout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addComponent(jLabelItem2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelItemName2)
                .addGap(18, 18, 18)
                .addGroup(jPanelItem2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinnerItem2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBuy2)))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jPanelItem1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(119, 119, 119)
                .addComponent(jPanelItem2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(292, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanelItem2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelItem1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(738, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel4, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void spinnerChecker(JSpinner spinner, int itemPrice) {
        int spinnerChecker = (Integer) spinner.getValue();
        if (spinnerChecker <= 0) {
            JOptionPane.showMessageDialog(null, "Mohon masukkan jumlah barang anda !!!");
        } else {
            int totalItemPrice = itemPrice * (Integer) jSpinnerItem1.getValue();
            System.out.println("harus membayar sebesar : " + totalItemPrice);
        }
    }

    private void jLabelShopMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelShopMouseClicked
        // TODO add your handling code here:
        cardMenu.show(jPanel2, "card2");
    }//GEN-LAST:event_jLabelShopMouseClicked

    private void jLabelCartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCartMouseClicked
        // TODO add your handling code here:
        cardMenu.show(jPanel2, "card3");
    }//GEN-LAST:event_jLabelCartMouseClicked

    private void jLabelShopKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabelShopKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelShopKeyPressed

    private void jSpinnerItem1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jSpinnerItem1KeyPressed
        // TODO add your handling code here
    }//GEN-LAST:event_jSpinnerItem1KeyPressed

    private void jButtonBuy1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuy1ActionPerformed
        // TODO add your handling code here:
        spinnerChecker(jSpinnerItem1, 5000);
    }//GEN-LAST:event_jButtonBuy1ActionPerformed

    private void jSpinnerItem2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jSpinnerItem2KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jSpinnerItem2KeyPressed

    private void jButtonBuy2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuy2ActionPerformed
        // TODO add your handling code here:
        spinnerChecker(jSpinnerItem2, 3000);
    }//GEN-LAST:event_jButtonBuy2ActionPerformed

    private void jLabelDashBoard1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDashBoard1MouseClicked
        // TODO add your handling code here:
        cardMenu.show(jPanel2, "card4");
    }//GEN-LAST:event_jLabelDashBoard1MouseClicked

    private void jLabelCart1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCart1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelCart1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mockup2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mockup2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mockup2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mockup2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mockup2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBuy1;
    private javax.swing.JButton jButtonBuy2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelCart;
    private javax.swing.JLabel jLabelCart1;
    private javax.swing.JLabel jLabelDashBoard1;
    private javax.swing.JLabel jLabelGreeting1;
    private javax.swing.JLabel jLabelItem1;
    private javax.swing.JLabel jLabelItem2;
    private javax.swing.JLabel jLabelItemName1;
    private javax.swing.JLabel jLabelItemName2;
    private javax.swing.JLabel jLabelShop;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanelItem1;
    private javax.swing.JPanel jPanelItem2;
    private javax.swing.JSpinner jSpinnerItem1;
    private javax.swing.JSpinner jSpinnerItem2;
    // End of variables declaration//GEN-END:variables
}

